title: SimSpin
description: A package for producing mock observations of particle simulations.
theme: jekyll-theme-minimal
show_downloads: true
logo: /assets/img/logo.png
github:
  repository_url: https://github.com/kateharborne/SimSpin
  citation_url: https://github.com/kateharborne/SimSpin/blob/master/CITATION.cff
  ads_url: https://ui.adsabs.harvard.edu/abs/2019ascl.soft03006H/abstract
  owner_url: https://github.com/kateharborne
navigation:
  - title: Home
    url: /
  - title: Installation
    url: installation
  - title: Basic Usage
    url: basic_usage
  - title: Documentation
    url: documentation
  - title: Examples
    url: examples