title: SimSpin
description: The purpose of [this guide](https://kateharborne.github.io/SimSpin/) is to act as a reference for users. 
It outlines the intended functionality and processes available in the `SimSpin` code. 
This is both a form of documentation and a collection of examples. 
For a basic walk-through of installing `SimSpin` and running a simple observation, please see the links below -

### Quick links:

  1. [Installation](https://kateharborne.github.io/SimSpin/installation)
  1. [Basic Usage](https://kateharborne.github.io/SimSpin/basic_usage)
  1. [Documentation](https://kateharborne.github.io/SimSpin/documentation) 

theme: jekyll-theme-minimal
show_downloads: true
logo: /assets/img/logo.png
github:
  repository_url: https://github.com/kateharborne/SimSpin
  zip_url: https://github.com/kateharborne/SimSpin/archive/refs/tags/v2.0.6.zip
  tar_url: https://github.com/kateharborne/SimSpin/archive/refs/tags/v2.0.6.tar.gz
  owner_url: https://github.com/kateharborne
