# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Constructing galaxy observation data from the Gadget output file data.
#'
#' The purpose of this function is to produce the observable features of simulation data when
#' taking mock IFU observations. It accepts the Gadget particle information output from the
#' \code{snapshot::snapread} function and returns the observable galaxy properties projected at a
#' user supplied inclination.
#'
#' @param part_data The data frame output by \code{snapshot::snapread} for galaxy simulation data
#'  from Gadget.
#' @param centre A logical that tells the function to centre the galaxy about its centre of mass or
#'  not (i.e. TRUE or FALSE).
#' @param inc_rad The observed inclination angle in radians.
#' @return Returns a data frame containing the original particle information plus the observed
#'  z-position (\code{$z_obs}), observed radial position (\code{$r_obs}) and the observed line of
#'  sight velocity (\code{$vy_obs}) at the given inclination.
#' @examples
#'   data = snapshot::snapread(system.file("extdata", 'S0_vignette', package="SimSpin"))
#'   data$part$part_type = rep(0,length(data$part))
#'
#'   obs_galaxy(part_data = data$part,
#'              centre    = TRUE,
#'              inc_rad   = 0)
#' @export
obs_galaxy <- function(part_data, centre, inc_rad) {
    .Call('SimSpin_obs_galaxy', PACKAGE = 'SimSpin', part_data, centre, inc_rad)
}

#' Constructing galaxy simulation data from the Gadget output file data
#'
#' The purpose of this function is to produce the extra kinematic features for simulation data in
#' spherical polar coordinates. It accepts the Gadget particle information output from the
#' \code{snapshot::snapread} function and returns several additional galaxy properties that are
#' useful for deriving the galaxy kinematics.
#'
#' @param part_data The data frame output by \code{snapshot::snapread} for galaxy simulation data
#'  in Gadget format.
#' @param centre A logical that tells the function to centre the galaxy about its centre of mass
#'  or not (i.e. TRUE or FALSE).
#' @return Returns a data frame containing the particle \code{$ID}, \code{$x-}, \code{$y-} and
#'  \code{$z-}positions and corresponding velocities (\code{$vx, $vy } and \code{$vz}), along with
#'  the spherical polar coordinates (\code{$r}, \code{$theta} and \code{$phi}) and associated
#'  velocities (\code{$vr}, \code{$vtheta} and \code{$vphi}), the cylindrical radial coordinate
#'  and its associated velocity (\code{$cr} and \code{$vcr}) and the mass of each particle
#'  (\code{$Mass}) and their angular momentum components (\code{$Jx}, \code{$Jy},\code{$Jz}).
#' @examples
#'   data = snapshot::snapread(system.file("extdata", 'S0_vignette', package="SimSpin"))
#'   data$part$part_type = rep(0,length(data$part))
#'
#'   sim_galaxy(part_data = data$part,
#'              centre    = TRUE)
#' @export
sim_galaxy <- function(part_data, centre) {
    .Call('SimSpin_sim_galaxy', PACKAGE = 'SimSpin', part_data, centre)
}

